disabled_rules:
  - trailing_whitespace
  - xctfail_message
  - multiple_closures_with_trailing_closure
  - closure_parameter_position
nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 10

line_length:
  warning: 160
  error: 200

warning_threshold: 5

excluded:
  - Pods
  - vendor
