disabled_rules:
  - trailing_whitespace
  - xctfail_message
  - multiple_closures_with_trailing_closure
  - closure_parameter_position
  - identifier_name
  - valid_ibinspectable

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 10

function_parameter_count:
  warning: 6

line_length:
  warning: 128
  error: 160

function_body_length:
  warning: 50

warning_threshold: 5

excluded:
  - Pods
  - vendor
