//
//  Stage.xcconfig
//  TimeTable
//
//  Created by Piotr Pawluś on 02/10/2018.
//  Copyright © 2018 Railwaymen. All rights reserved.
//

TT_APP_NAME = ${STAGE_APP_NAME}
TT_APP_VERSION = 0.1
TT_APP_BUNDLE_ID = ${STAGE_APP_BUNDLE_ID}
TT_TEST_BUNDLE_ID = ${APP_TEST_BUNDLE_ID}
TT_UI_TEST_BUNDLE_ID = ${APP_TEST_UI_BUNDLE_ID}
TT_DEVELOPMENT_TEAM_ID = ${DEVELOPMENT_TEAM_ID}
TT_ORGANIZATION_NAME = ${DEVELOPMENT_ORGANIZATION_NAME}
